census/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.i18n import JavaScriptCatalog

from users.views import LanguageView, error_404, error_500

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('users.urls', 'users'), 'user')),
    path('translate/', include('rosetta.urls')),
    path('lang/<str:lang>', LanguageView.as_view(), name='lang'),
    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    path('api/', include('users.api.urls', namespace='api-users')),
]

handler404 = error_404
handler500 = error_500

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

root/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.i18n import JavaScriptCatalog

from users.views import LanguageView, error_404, error_500

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('users.urls', 'users'), 'user')),
    path('translate/', include('rosetta.urls')),
    path('lang/<str:lang>', LanguageView.as_view(), name='lang'),
    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    path('api/', include('users.api.urls', namespace='api-users')),
]

handler404 = error_404
handler500 = error_500

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/forms.py
from django import forms
from django.forms import TextInput, PasswordInput
from django.utils.translation import ugettext_lazy as _
from users.models import phone, Employee, District, Territory, SiteSettings


class TelInput(TextInput):
    input_type = 'tel'


class HiddenSelectInput(forms.Select):
    input_type = 'hidden'


class UserLoginForm(forms.Form):
    number = forms.CharField(
        validators=[phone],
        widget=TelInput(attrs={'placeholder': '550XXXXXX',
                               'pattern': '^\d{9}$'}),
        label=_('number'))

    password = forms.CharField(
        widget=PasswordInput(),
        label=_('password'))

    next = forms.CharField(
        widget=TextInput(attrs={'hidden': True}),
        required=False)

    class Meta:
        fields = ['number', 'password', 'next']


class EmployeeCreateForm(forms.ModelForm):
    class Meta:
        model = Employee
        exclude = ['qrcode', 'agreement', 'login', 'password', 'is_badge_printed', 'is_badge_returned', 'photo',
                   'dismissed']
        widgets = {
            'number': TelInput(attrs={'class': 'form-control masked', 'placeholder': '555 500 000',
                                      'pattern': '\d{9}'}),
            'last_name': TextInput(attrs={'class': 'form-control'}),
            'first_name': TextInput(attrs={'class': 'form-control'}),
            'patronymic': TextInput(attrs={'class': 'form-control'}),
            'gender': forms.Select(attrs={'class': 'form-control'}),
            'birth_day': forms.DateInput(
                attrs={'class': 'date form-control', 'placeholder': 'Мисалы: 31.12.2004'},
                format='%d.%m.%Y'),
            'serial': forms.Select(attrs={'style': 'text-transform: uppercase;', 'class': 'form-control'}),
            'passport_num': TelInput(attrs={'class': 'form-control'}),
            'address': TextInput(attrs={'class': 'form-control'}),
            'authority': TextInput(attrs={'style': 'text-transform: uppercase;', 'class': 'form-control'}),
            'PIN': TelInput(attrs={'class': 'form-control'}),
            'education': forms.Select(attrs={'class': 'form-control'}),
            'role': forms.Select(attrs={'class': 'form-control'}),
            'department': TextInput(attrs={'class': 'form-control'}),
            'sector': TextInput(attrs={'class': 'form-control'}),
            'plot': TextInput(attrs={'class': 'form-control'}),
            'territory': forms.Select(attrs={'class': 'form-control'}),
            'workday': forms.Select(attrs={'class': 'form-control'}),
            'district': forms.HiddenInput(
                attrs={'class': 'text-dark font-weight-bold form-control'}),
        }

    def __init__(self, user, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['district'].queryset = District.objects.filter(user=user)
        self.fields['district'].initial = District.objects.first()
        self.fields['district'].empty_label = None
        self.fields['territory'].queryset = Territory.objects.filter(district=user.district)


class EmployeeUpdateForm(forms.ModelForm):
    class Meta:
        model = Employee
        exclude = ['qrcode', 'agreement', 'login', 'password', 'district', 'photo']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        initial = kwargs.get('initial')

        territory = initial.get('territory')

        self.fields['territory'].queryset = territory


class PhotoUpdateForm(forms.ModelForm):
    x1 = forms.CharField(widget=forms.HiddenInput(), required=False)
    y1 = forms.CharField(widget=forms.HiddenInput(), required=False)
    x2 = forms.CharField(widget=forms.HiddenInput(), required=False)
    y2 = forms.CharField(widget=forms.HiddenInput(), required=False)

    class Meta:
        model = Employee
        fields = ['photo']

templates/employee/detail.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% load replace_asterisk %}

{% block title %}
    {% trans 'Employee' %}
{% endblock %}
{% block content %}

    <section class="section-detail mt-5">
        <div class="container">
            {% if not object.dismissed %}
                <div class="detail__header">
                    <h1 class="detail-header__certificate">{% trans 'Certificate' %} &#8470;{{ object.agreement }}</h1>
                    <h1 class="detail-header__role">{{ object.get_role }}</h1>
                </div>
                <div class="detail__items d-flex">
                    <div class="image__item">
                        {% if object.photo %}
                            <img src="{{ object.photo.url }}" alt="" class="image">
                        {% else %}
                            <img src="{% static 'img/nophoto.png' %}" alt="" class="image">
                        {% endif %}
                    </div>
                    <div class="employee__info mr-5 ml-5 my-auto">
                        <div class="employee-info">
                            <span>Фамилиясы:</span>
                            {% if user.is_authenticated %}
                                <span>{{ object.last_name }}</span>
                            {% else %}
                                <span>{{ object.last_name|cover:"*" }}</span>
                            {% endif %}
                        </div>
                        <div class="employee-info">
                            <span>Аты:</span>
                            {% if user.is_authenticated %}
                                <span>{{ object.first_name }}</span>
                            {% else %}
                                <span>{{ object.first_name|cover:"*" }}</span>
                            {% endif %}
                        </div>
                        {% if object.patronymic %}
                            <div class="employee-info">
                                <span>Атасынын аты:</span>
                                {% if user.is_authenticated %}
                                    <span>{{ object.patronymic }}</span>
                                {% else %}
                                    <span>{{ object.patronymic|cover:"*" }}</span>
                                {% endif %}
                            </div>
                        {% endif %}
                    </div>
                </div>
                {% else %}
                <div class="alert alert-warning text-center">
                    <h1>{% trans 'This employee is dismissed' %}</h1>
                </div>
            {% endif %}
        </div>

        {% if not user.is_authenticated %}
            <div class="mt-5">
                <p class="text-center">Коопсуздук эрежелерин сактоо максатында ысымдар толук эмес түрдө берилген</p>
            </div>
        {% endif %}

    </section>

{% endblock %}

{% block js %}
    <script>
        $(document).ready(function () {
            if (window.localStorage) {
                if (!localStorage.getItem('firstLoad')) {
                    localStorage['firstLoad'] = true;
                    window.location.reload();
                } else {
                    localStorage.removeItem('firstLoad');
                }
            }
        });
    </script>
{% endblock js %}

templates/employee/list.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% load widget_tweaks %}
{% load users_extras %}
{% block title %}
    {% trans 'Employees' %}
{% endblock %}
{% block content %}
        <div class="symbols no-print">
        <button value="Ө" onclick="insertSymbol(this)" class="symbol">Ө</button>
        <button value="Ү" onclick="insertSymbol(this)" class="symbol">Ү</button>
        <button value="Ң" onclick="insertSymbol(this)" class="symbol">Ң</button>
        <button value="ө" onclick="insertSymbol(this)" class="symbol">ө</button>
        <button value="ү" onclick="insertSymbol(this)" class="symbol">ү</button>
        <button value="ң" onclick="insertSymbol(this)" class="symbol">ң</button>
    </div>
    <div class="container">
        <div>
            <form method="get">
                <div class="form-row">
                    {% for field in filterset.form.visible_fields %}
                        <div class="form-group col-md-2">
                            <label for="id_{{ field.label|lower }}">{{ field.label }}</label>
                            {% render_field field class="form-control" autocomplete="off" %}
                        </div>
                    {% endfor %}
                </div>
                <button type="submit" class="search-btn">{% trans 'Search' %}</button>
            </form>
        </div>

        <table class="table table-hover mt-5" id="myTable" data-card-width="1000">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">{% trans 'Number' %}</th>
                <th scope="col">{% trans 'Name' %}</th>
                <th scope="col">{% trans 'Surname' %}</th>
                <th scope="col">{% trans 'Agreement' %}</th>
                <th scope="col">{% trans 'Role' %}</th>
            </tr>
            </thead>
            <tbody>
            {% for object in object_list %}
                <tr>
                    <td>{{ forloop.counter|mul:page_obj.number }}</td>
                    <td><a href="{% url 'users:update' object.pk %}">{{ object.number }}</a></td>
                    <td>{{ object.first_name }}</td>
                    <td>{{ object.last_name }}</td>
                    <td><a href="{% url 'users:agreement_detail' object.pk %}">№ {{ object.agreement }}</a></td>
                    <td>{{ object.get_role }}</td>
                </tr>
            {% endfor %}

            </tbody>
        </table>

        {% if is_paginated %}
            <div class="d-flex">
                <nav aria-label="Employee list pagination" class="mx-auto">
                    <ul class="pagination">
                        {% if page_obj.has_previous %}
                            <li class="page-item">
                                <a class="page-link" href="?{% param_replace page=page_obj.previous_page_number %}">&laquo;</a>
                            </li>
                        {% else %}
                            <li class="page-item disabled">
                        <span class="page-link">
                            <span aria-hidden="true">&laquo;</span>
                            <span class="sr-only">Мурдакы барак</span>
                        </span>
                            </li>
                        {% endif %}
                        {% for i in paginator.page_range %}
                            {% if i <= page_obj.number|add:5 and i >= page_obj.number|add:-5 %}
                                {% if page_obj.number == i %}
                                    <li class="page-item active"><span class="page-link">{{ forloop.counter }} <span
                                            class="sr-only">(current)</span></span></li>
                                {% else %}
                                    <li class="page-item">
                                        <a class="page-link"
                                           href="?{% param_replace page=forloop.counter %}">{{ forloop.counter }}</a>
                                    </li>
                                {% endif %}
                            {% endif %}
                        {% endfor %}
                        {% if page_obj.has_next %}
                            <li class="page-item">
                                <a class="page-link"
                                   href="?{% param_replace page=page_obj.next_page_number %}">&raquo;</a>
                            </li>
                        {% else %}
                            <li class="page-item disabled">
                        <span class="page-link">
                            <span aria-hidden="true">&raquo;</span>
                            <span class="sr-only">Кийинки барак</span>
                        </span>
                            </li>
                        {% endif %}
                    </ul>
                </nav>
            </div>
        {% endif %}
    </div>
{% endblock %}

{% block js %}
    <script>setMobileTable('table');</script>
    <script>
        $(document).ready(function () {
            $('#id_number').mask('000000000', {'translation': {9: {pattern: '9'}, 6: {pattern: '6'}}});
        });
    </script>
{% endblock js %}