census/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.i18n import JavaScriptCatalog

from users.views import LanguageView, error_404, error_500

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('users.urls', 'users'), 'user')),
    path('translate/', include('rosetta.urls')),
    path('lang/<str:lang>', LanguageView.as_view(), name='lang'),
    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    path('api/', include('users.api.urls', namespace='api-users')),
]

handler404 = error_404
handler500 = error_500

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

root/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.i18n import JavaScriptCatalog

from users.views import LanguageView, error_404, error_500

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('users.urls', 'users'), 'user')),
    path('translate/', include('rosetta.urls')),
    path('lang/<str:lang>', LanguageView.as_view(), name='lang'),
    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    path('api/', include('users.api.urls', namespace='api-users')),
]

handler404 = error_404
handler500 = error_500

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/models.py
import os

from django.conf import settings
from django.contrib.auth.base_user import BaseUserManager, AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin
from django.core.cache import cache
from django.core.files.uploadedfile import InMemoryUploadedFile
from django.core.validators import RegexValidator
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.urls import reverse
from django.utils import dateformat
from django.utils.translation import ugettext_lazy as _
from num2words import num2words

phone = RegexValidator(regex=r'^\d{9}$',
                       message=_("must be in 555 500 000 format!"))


class UserManager(BaseUserManager):

    def _create_user(self, number, password, is_staff, is_superuser, **extra_fields):
        user = self.model(
            number=number,
            is_staff=is_staff,
            is_superuser=is_superuser,
            **extra_fields
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, number, password, **extra_fields):
        return self._create_user(number, password, False, False, **extra_fields)

    def create_superuser(self, number, password, **extra_fields):
        user = self._create_user(number, password, True, True, **extra_fields)
        user.save(using=self._db)
        return user


class User(AbstractBaseUser, PermissionsMixin):
    number = models.CharField(_('number'), max_length=255, validators=[phone],
                              unique=True)
    region = models.ForeignKey('Region', models.CASCADE, verbose_name=_('region'), null=True)
    district = models.ForeignKey('District', models.CASCADE, verbose_name=_('district'), null=True)
    is_staff = models.BooleanField(_('is staff'), default=True)
    is_superuser = models.BooleanField(_('super user'), default=False)

    USERNAME_FIELD = 'number'
    EMAIL_FIELD = 'number'
    objects = UserManager()

    class Meta(AbstractBaseUser.Meta):
        verbose_name = _('User')
        verbose_name_plural = _('Users')
        permissions = [
            ("can_print_badge", "Can print a badge"),
            ("can_print_agreement", "Can print an agreement"),
        ]

    def __str__(self):
        return f'{self.number}'


class Region(models.Model):
    REGION_CHOICES = (
        ('chu', 'Чүй'),
        ('osh', 'Ош'),
        ('bat', 'Баткен'),
        ('jal', 'Жалал-Абад'),
        ('tal', 'Талас'),
        ('nar', 'Нарын'),
        ('kol', 'Ысык-Көл'),
        ('bis', 'г.Бишкек'),
        ('oshc', 'г.Ош'),
    )
    name = models.CharField(_('name'), max_length=9, choices=REGION_CHOICES, unique=True)
    address = models.CharField(_('address'), max_length=255)
    stat = models.CharField(_('stat'), max_length=255, null=True)

    class Meta:
        verbose_name = _('Region')
        verbose_name_plural = _('Regions')

    def __str__(self):
        return f'{dict(self.REGION_CHOICES)[self.name]}'


class District(models.Model):
    name = models.CharField(_('name'), max_length=55)
    region = models.ForeignKey(Region, models.CASCADE, verbose_name=_('region'))
    gov_admin = models.CharField(max_length=255, verbose_name='Мам админстрация башчы (ААТ)')
    stat_admin = models.CharField(max_length=255, verbose_name='Статистика башчы (ААТ)')
    counter = models.CharField(max_length=6, default='000001')
    center = models.CharField(_('center of district'), max_length=255, null=True, blank=True)
    agreement_ky = models.CharField(max_length=255, null=True, blank=True)
    agreement_ru = models.CharField(max_length=255, null=True, blank=True)
    stat_address = models.CharField(max_length=255, null=True, blank=True)
    did = models.CharField(max_length=2, null=True, blank=True)

    class Meta:
        verbose_name = _('District')
        verbose_name_plural = _('Districts')

    def __str__(self):
        return f'{self.name}'


def increment_territory_country():
    last_territory = Territory.objects.order_by('counter').last()
    if not last_territory:
        return '0001'
    return '{:04}'.format(int(last_territory.counter) + 1)


class Territory(models.Model):
    name = models.CharField(_('name'), max_length=90)
    code = models.CharField(_('code'), max_length=14, unique=True)
    district = models.ForeignKey(District, models.CASCADE)
    counter = models.CharField(max_length=4, default=increment_territory_country,
                               editable=False, unique=True)

    class Meta:
        verbose_name = _('Territory')
        verbose_name_plural = _('Territories')
        ordering = ['code']

    def __str__(self):
        return f'{self.name}'


class Employee(models.Model):
    GENDER_CHOICES = (
        ('2', _('male')),
        ('1', _('female')),
    )
    ROLE_CHOICES = (
        ('cor', _('Coordinator')),
        ('enum', _('Enumerator')),
        ('enum1', _('Enumerator1')),
        ('ins', _('Instructor')),
    )
    EDUCATION_CHOICES = (
        ('1', _('bachelor')),
        ('2', _('specialist')),
        ('3', _('master')),
        ('4', _('incomplete higher education')),
        ('5', _('specialized secondary education')),
        ('6', _('initial vocational training')),
        ('7', _('general secondary education')),
        ('8', _('lower secondary education'))
    )
    WORKDAY_CHOICES = (
        ('full', _('full time work')),
        ('half', _('half time work'))
    )

    number = models.CharField(_('number'), max_length=255, validators=[phone], unique=True,
                              error_messages={'unique': "Мундай номер бар."})
    last_name = models.CharField(_('last name'), max_length=45)
    first_name = models.CharField(_('first name'), max_length=45)
    patronymic = models.CharField(_('patronymic'), max_length=45, null=True, blank=True)
    gender = models.CharField(_('gender'), max_length=1, choices=GENDER_CHOICES, default='2')
    birth_day = models.DateField(_('birth day'))
    serial = models.CharField(_('serial'), max_length=2, choices=(('ID', 'ID'), ('AN', 'AN'), ('AC', 'AC')),
                              default='ID')
    passport_num = models.CharField(_('number of passport'), max_length=7)
    address = models.CharField(_('address'), max_length=255)
    authority = models.CharField(_('authority'), max_length=10)
    PIN = models.CharField(_('PIN'), max_length=14, unique=True)
    photo = models.ImageField(_('photo'), upload_to='users/img')
    education = models.CharField(_('education'), max_length=1, choices=EDUCATION_CHOICES, default=1)
    role = models.CharField(_('role'), max_length=50, choices=ROLE_CHOICES, default='cor')
    department = models.PositiveSmallIntegerField(_('census department'), default=1)
    sector = models.PositiveSmallIntegerField(_('coordinator sector'), default=1)
    plot = models.PositiveSmallIntegerField(_('enumerator plot'), default=1)
    district = models.ForeignKey(District, models.SET_NULL, verbose_name=_('district'), null=True, blank=True)
    territory = models.ForeignKey(Territory, models.SET_NULL, verbose_name=_('territory'), null=True, blank=True)
    workday = models.CharField(_('workday'), max_length=4, choices=WORKDAY_CHOICES, default='full')
    agreement = models.CharField(_('agreement'), max_length=6)
    date_joined = models.DateTimeField(_('date joined'), auto_now_add=True)
    is_badge_printed = models.BooleanField(_('is badge printed?'), default=False)
    is_badge_returned = models.BooleanField(_('is badge returned?'), default=False)
    dismissed = models.BooleanField(_('Dismissed?'), default=False)

    class Meta:
        verbose_name = _('Employee')
        verbose_name_plural = _('Employees')
        unique_together = (('district', 'agreement'), ('serial', 'passport_num'))
        ordering = ['-id']

    def get_absolute_url(self):
        return reverse('users:detail', args=[self.id])

    @property
    def get_role(self):
        return dict(Employee.ROLE_CHOICES).get(self.role)

    def __str__(self):
        return f'{self.first_name}'


@receiver(post_save, sender=Employee)
def set_agreement_number(sender, instance, created=False, **kwargs):
    if created:
        instance.agreement = "{:02}{:04}".format(int(instance.district.did), int(instance.district.counter))
        instance.district.counter = "{:06}".format(int(instance.district.counter) + 1)
        instance.district.save()
        instance.save()


class SingletonModel(models.Model):
    class Meta:
        abstract = True

    def delete(self, *args, **kwargs):
        pass

    def set_cache(self):
        cache.set(self.__class__.__name__, self)

    def save(self, *args, **kwargs):
        self.pk = 1
        super().save(*args, **kwargs)

    @classmethod
    def load(cls):
        obj, created = cls.objects.get_or_create(pk=1)
        return obj


class SiteSettings(SingletonModel):
    ROLE_CHOICES = (
        ('enum', _('Enumerator')),
        ('enum1', _('Enumerator1')),
        ('ins', _('Instructor')),
        ('cor', _('Coordinator')),

    )
    role = models.CharField(max_length=50, choices=ROLE_CHOICES, null=True)

    class Meta:
        verbose_name = 'Настройки сайта'
        verbose_name_plural = 'Настройки сайта'

    def __str__(self):
        return "Настройки сайта"


class RoleInfo(models.Model):
    ROLE_CHOICES = (
        ('enum', _('Enumerator')),
        ('enum1', _('Enumerator1')),
        ('ins', _('Instructor')),
        ('cor', _('Coordinator')),

    )
    site_settings = models.ForeignKey(SiteSettings, on_delete=models.CASCADE)
    role = models.CharField(max_length=50, choices=ROLE_CHOICES, null=True)
    salary = models.PositiveIntegerField(null=True)
    workday_start_date = models.DateField(null=True)
    workday_end_date = models.DateField(null=True)
    days_off = models.CharField(max_length=255, null=True, blank=True)
    agreement_day = models.DateField(null=True, blank=True)

templates/base.html
{% load static %}
{% load i18n %}
{% load admin_urls %}
<!DOCTYPE html>
{% get_current_language as curr %}
<html lang="{{ curr }}" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link rel="shortcut icon" type="image/ico" href="{% static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    {% block head %}{% endblock head %}
    <link rel="stylesheet" href="{% static 'css/style-extededexcluded.css' %}">
    <link rel="stylesheet" href="{% static 'css/cropper.css' %}">
    <link rel="stylesheet" media="print" href="{% static 'css/print.css' %}"/>
    <title> {% block title %}{% endblock title %} </title>

</head>
<body>

<header class="header no-print">
    <div class="header__top">
        <div class="container d-flex">
            <a href="#"><img src="{% static 'img/logo.png' %}" alt="logo"></a>
            <span class="mx-auto top-sentence no-print">Кыргыз Республикасынын 2020-жылдагы эл жана турак жай каттоосу</span>
        </div>
    </div>

    <div class="header-container">
        <div class="container">
            <div class="header-main d-flex flex-row align-items-center justify-content-start">
                <nav class="main-nav-container d-flex w-100">
                    <ul class="main-nav">
                        {% if request.user.is_authenticated %}
                            <li><a href="{% url 'users:home' %}">{% trans 'Home' %}</a></li>
                        {% endif %}
                        {% if request.user.is_staff %}
                            <li><a href="{% url 'users:list' %}">{% trans 'Employees' %}</a></li>
                        {% endif %}
                        {% if perms.users.change_employee %}
                            <li><a href="{% url 'admin:index' %}">{% trans 'admin' %}</a></li>
                        {% endif %}
                    </ul>

                    <ul class="main-nav main-nav__left ml-auto">
                        <div class="language-picker">
                            <div class="language-picker__items">
                                {% get_available_languages as langs %}
                                {% for lang, val in langs %}
                                    <a class="language-picker__item {% ifequal lang curr %}active{% endifequal %}"
                                       href="{% url 'lang' lang %}">{% if lang == 'ky' %}
                                        кыр{% elif lang == 'ru' %}рус{% endif %}</a>
                                {% endfor %}
                            </div>
                        </div>
                        <li>
                            {% if request.user.is_authenticated %}
                                <a href="{% url 'users:logout' %}">{% trans 'Logout' %}</a>
                            {% else %}
                                {% if request.path != '/' %}
                                    <a href="{% url 'users:login' %}">{% trans 'Login' %}</a>
                                {% endif %}
                            {% endif %}
                        </li>
                        <li>
                            {% if request.user.is_authenticated %}
                                <a href="#"><i class="fa fa-user"></i> {{ request.user }}</a>
                            {% endif %}
                        </li>
                    </ul>
                </nav>
            </div>
        </div>
    </div>

    <div class="header-mobile">
        <div class="header-toggle">
            <i class="fa fa-bars" aria-hidden="true"></i>
        </div>

        <div class="header-mobile__item header-right-menu">
            <div class="header-right-menu__item header-button">
                {% get_available_languages as langs %}
                {% for lang, val in langs %}
                    <a class="language-picker__item {% ifequal lang curr %}active{% endifequal %}"
                       href="{% url 'lang' lang %}">{% if lang == 'ky' %}
                        кыр{% elif lang == 'ru' %}рус{% endif %}</a>
                {% endfor %}
            </div>
        </div>
    </div>
</header>

<div class="mobile-menu">
    <div class="mobile-menu__scrollable">
        <div class="mobile-menu__top">
            <div class="mobile-menu__logo">
                <span>УСК</span>
            </div>
            <div class="mobile-menu__close-menu">
                <i class="fa fa-times"></i>
            </div>
        </div>

        <div class="mobile-menu__links">
            <a href="{% url 'users:home' %}" class="mobile-menu__link">
                <i class="fa fa-home"></i> {% trans 'Home' %}</a>
            <a href="{% url 'users:list' %}" class="mobile-menu__link">
                <i class="fa fa-users"></i> {% trans 'Employees' %}</a>
            {% if request.user.is_authenticated %}
                <a href="{% url 'users:logout' %}" class="mobile-menu__link">
                    <i class="fa fa-sign-out"></i> {% trans 'Logout' %}</a>
            {% else %}
                <a href="{% url 'users:login' %}" class="mobile-menu__link">
                    <i class="fa fa-sign-in"></i> {% trans 'Login' %}
                </a>
            {% endif %}
            {% if perms.users.change_employee %}
                <li><a href="{% url 'admin:index' %}">{% trans 'admin' %}</a></li>
            {% endif %}
        </div>
    </div>
</div>

<div class="container-fluid messages no-print">
    {% if messages %}
        {% for message in messages %}
            <div class="alert{% if message.extra_tags %} {{ message.tags }} {% endif %} alert-dismissible "
                 role="alert">
                <strong>{{ message }}</strong>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% endfor %}
    {% endif %}
</div>

<div class="container main-content mb-5">
    {% block content %}{% endblock content %}
</div>


<!-- jQuery library -->
<script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>

<!-- Popper JS -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/masking-input.js' %}" data-autoinit="true"></script>

<script src="{% static 'js/custom.js' %}"></script>
<script src="{% static 'js/dirtydeals.js' %}"></script>
<script src="{% static 'js/cropper.js' %}"></script>
{% block js %}{% endblock js %}
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% load widget_tweaks %}
{% block title %}
    {% trans 'Home' %}
{% endblock %}
{% block content %}
    <div class="symbols no-print">
        <button value="Ө" onclick="insertSymbol(this)" class="symbol">Ө</button>
        <button value="Ү" onclick="insertSymbol(this)" class="symbol">Ү</button>
        <button value="Ң" onclick="insertSymbol(this)" class="symbol">Ң</button>
        <button value="ө" onclick="insertSymbol(this)" class="symbol">ө</button>
        <button value="ү" onclick="insertSymbol(this)" class="symbol">ү</button>
        <button value="ң" onclick="insertSymbol(this)" class="symbol">ң</button>
    </div>
    <section>
        <div class="container">
            <h5 class="mt-5 text-center">{% trans 'Employee Creation Form' %}</h5>
            <form action="{% url 'users:home' %}" method="post" enctype="multipart/form-data" data-ajax="false">
                {% csrf_token %}
                <div class="row">
                    {% for field in form.visible_fields %}
                        <div class="form-group col-md-7 col-sm-12 mx-auto disabled-wrap-box">
                            <label for="id_{{ field.label|lower }}" class="col-form-label">{{ field.label }}</label>
                            {{ field }}
                            {{ field.help }}
                            {% if field.errors %}
                                <div class="invalid-feedback">
                                    {% for error in field.errors %}
                                        <small>
                                            {{ error|striptags }}
                                        </small><br>
                                    {% endfor %}
                                </div>
                            {% endif %}
                        </div>
                    {% endfor %}
                    {% for field in form.hidden_fields %}
                        <div style="display:none;">{{ field }}</div>
                        {% if field.errors %}
                            {% for error in errors %}
                                <small class="alert text-danger">{{ error|striptags }}</small>
                            {% endfor %}
                        {% endif %}
                    {% endfor %}
                </div>

                <div class="row">
                    <div class="col-md-7 col-sm-12 mx-auto mt-5">
                        <button type="submit" class="btn-full btn-add">{% trans 'Add' %}</button>
                    </div>
                </div>
            </form>
        </div>
    </section>

{% endblock %}
{% block js %}
    <script>
        $(document).ready(function () {
            $('.masked').mask('000000000');
            $('.date').mask('00.00.0000');

            let role = $('#id_role option:selected').val();

            if (role == 'cor') {
                $('#id_department').parents('.form-group').css({
                    "display": "block"
                });
                $('#id_sector').parents('.form-group').css({
                    "display": "none"
                });
                $('#id_plot').parents('.form-group').css({
                    "display": "none"
                });
            } else if (role == 'ins') {
                $('#id_department').parents('.form-group').css({
                    "display": "block"
                });
                $('#id_sector').parents('.form-group').css({
                    "display": "block"
                });
                $('#id_plot').parents('.form-group').css({
                    "display": "none"
                });
            } else {
                $('#id_department').parents('.form-group').css({
                    "display": "block"
                });
                $('#id_sector').parents('.form-group').css({
                    "display": "block"
                });
                $('#id_plot').parents('.form-group').css({
                    "display": "block"
                });
            }

            $('#id_role').change(function () {
                let role = $("#id_role option:selected").val();
                if (role == 'cor') {
                    $('#id_department').parents('.form-group').css({
                        "display": "block"
                    });
                    $('#id_sector').parents('.form-group').css({
                        "display": "none"
                    });
                    $('#id_plot').parents('.form-group').css({
                        "display": "none"
                    });
                } else if (role == 'ins') {
                    $('#id_department').parents('.form-group').css({
                        "display": "block"
                    });
                    $('#id_sector').parents('.form-group').css({
                        "display": "block"
                    });
                    $('#id_plot').parents('.form-group').css({
                        "display": "none"
                    });
                } else {
                    $('#id_department').parents('.form-group').css({
                        "display": "block"
                    });
                    $('#id_sector').parents('.form-group').css({
                        "display": "block"
                    });
                    $('#id_plot').parents('.form-group').css({
                        "display": "block"
                    });
                }
            });

            $('#id_none').keypress(function (e) {
                if (e.which == 13) {
                    let pin = $(this).val();
                    let serial = $('#id_serial').val();
                    let passport_num = $('#id_passport_num').val();
                    let name = document.getElementById('id_first_name');
                    let surname = document.getElementById('id_last_name');
                    let patronymic = document.getElementById('id_patronymic');
                    let gender = document.getElementById('id_gender');
                    let date_of_birth = document.getElementById('id_birth_day');
                    let address = document.getElementById('id_address');
                    $.ajax({
                        url: "{% url 'users:load_data_by_pin' %}",
                        data: {
                            'pin': pin,
                            'serial': serial,
                            'passport_num': passport_num
                        },
                        dataType: 'json',
                        success: function (data) {
                            console.log(data);
                            if (data.is_exist) {
                                name.value = data.name;
                                surname.value = data.surname;
                                patronymic.value = data.patronymic;
                                gender.value = data.gender;
                                date_of_birth.value = data.dateOfBirth;
                                address.value = data.address;
                            } else {
                                alert(data.error_text);
                            }
                        }
                    });
                    e.preventDefault();
                    return false;
                }
            });
        });
    </script>
{% endblock js %}

templates/login.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% load widget_tweaks %}
{% block title %}
    {% trans 'Home' %}
{% endblock %}
{% block content %}

<section class="section__login">
    <div class="container">
        <div class="card card-container">
            <div class="profile-img-card">
                <img src="{% static 'img/avatar_2x.png' %}" alt="profile image" id="profile-img">
            </div>
            <form action="{% url 'users:login' %}" method="POST" class="form__login">
            {% csrf_token %}
            {% for field in form %}
                {% ifnotequal field.name 'next' %}
                <div class="form-group">
                    {% ifequal field.name 'number' %}
                        {% if field.errors %}
                            {% render_field field class="form-control masked is-invalid" placeholder='550XXXXXX' %}
                        {% else %}
                            {% render_field field class="form-control masked" placeholder='550XXXXXX' %}
                        {% endif %}
                    {% else %}
                        {% if field.errors %}
                            {% render_field field class="form-control is-invalid" placeholder=field.label %}
                        {% else %}
                            {% render_field field class="form-control" placeholder=field.label %}
                        {% endif %}
                    {% endifequal %}
                    {% if field.errors %}
                        <div class="invalid-feedback">
                        {% for error in field.errors %}
                            <small>{{ error|striptags }}</small><br>
                        {% endfor %}
                        </div>
                    {% endif %}
                </div>
                {% else %}
                    {% render_field field value=redirect_url %}
                {% endifnotequal %}
            {% endfor %}
            <button class="btn btn-lg btn-primary btn-block btn-signin" type="submit">{% trans 'Login' %}</button>
            </form>
        </div>
    </div>
</section>
{% endblock %}
{% block js %}
    <script src="{% static 'js/masking-input.js' %}" data-autoinit="true"></script>
    <script>
    $(document).ready(function () {
        $('.masked').mask('000000000');
    });
</script>
{% endblock %}