census/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.i18n import JavaScriptCatalog

from users.views import LanguageView, error_404, error_500

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('users.urls', 'users'), 'user')),
    path('translate/', include('rosetta.urls')),
    path('lang/<str:lang>', LanguageView.as_view(), name='lang'),
    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    path('api/', include('users.api.urls', namespace='api-users')),
]

handler404 = error_404
handler500 = error_500

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

root/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.i18n import JavaScriptCatalog

from users.views import LanguageView, error_404, error_500

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('users.urls', 'users'), 'user')),
    path('translate/', include('rosetta.urls')),
    path('lang/<str:lang>', LanguageView.as_view(), name='lang'),
    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    path('api/', include('users.api.urls', namespace='api-users')),
]

handler404 = error_404
handler500 = error_500

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/api/urls.py
from django.urls import path
from rest_framework.routers import DefaultRouter
from . import views

app_name = 'api-users'

router = DefaultRouter()
router.register(r'employees', views.EmployeeViewSet)

urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('employee_create/', views.EmployeeCreateView.as_view(), name='employee_create'),
    path('docs/', views.APIDocsView.as_view(), name='docs'),
    path('excel/', views.EmployeeExcel.as_view(), name='excel')
]

urlpatterns += router.urls

users/urls.py
from django.urls import path

from users.views import (LoginView,
                         LogoutView,
                         AgreementDetailView,
                         EmployeeListView,
                         EmployeeDetailView,
                         EmployeeUpdateView,
                         EmployeeDeleteView,
                         IndexView,
                         PhotoUpdateView,
                         load_territories_view,
                         load_districts_view, LoadDataByPINView)

urlpatterns = [
    path('', LoginView.as_view(), name='login'),
    path('home/', IndexView.as_view(), name='home'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('employee/list/', EmployeeListView.as_view(), name='list'),
    path('employee/<int:pk>/', EmployeeDetailView.as_view(), name='detail'),
    path('employee/update/<int:pk>/', EmployeeUpdateView.as_view(), name='update'),
    path('employee/delete/<int:pk>/', EmployeeDeleteView.as_view(), name='delete'),
    path('employee/agreement/<int:pk>/', AgreementDetailView.as_view(), name='agreement_detail'),
    path('ajax/load-districts/', load_districts_view, name='load_districts'),
    path('ajax/load-territories/', load_territories_view, name='load_territories'),
    path('ajax/update-photo/<int:pk>', PhotoUpdateView.as_view(), name='update_photo'),
    path('ajax/load-data-by-pin', LoadDataByPINView.as_view(), name='load_data_by_pin'),
]

users/models.py
import os

from django.conf import settings
from django.contrib.auth.base_user import BaseUserManager, AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin
from django.core.cache import cache
from django.core.files.uploadedfile import InMemoryUploadedFile
from django.core.validators import RegexValidator
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.urls import reverse
from django.utils import dateformat
from django.utils.translation import ugettext_lazy as _
from num2words import num2words

phone = RegexValidator(regex=r'^\d{9}$',
                       message=_("must be in 555 500 000 format!"))


class UserManager(BaseUserManager):

    def _create_user(self, number, password, is_staff, is_superuser, **extra_fields):
        user = self.model(
            number=number,
            is_staff=is_staff,
            is_superuser=is_superuser,
            **extra_fields
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, number, password, **extra_fields):
        return self._create_user(number, password, False, False, **extra_fields)

    def create_superuser(self, number, password, **extra_fields):
        user = self._create_user(number, password, True, True, **extra_fields)
        user.save(using=self._db)
        return user


class User(AbstractBaseUser, PermissionsMixin):
    number = models.CharField(_('number'), max_length=255, validators=[phone],
                              unique=True)
    region = models.ForeignKey('Region', models.CASCADE, verbose_name=_('region'), null=True)
    district = models.ForeignKey('District', models.CASCADE, verbose_name=_('district'), null=True)
    is_staff = models.BooleanField(_('is staff'), default=True)
    is_superuser = models.BooleanField(_('super user'), default=False)

    USERNAME_FIELD = 'number'
    EMAIL_FIELD = 'number'
    objects = UserManager()

    class Meta(AbstractBaseUser.Meta):
        verbose_name = _('User')
        verbose_name_plural = _('Users')
        permissions = [
            ("can_print_badge", "Can print a badge"),
            ("can_print_agreement", "Can print an agreement"),
        ]

    def __str__(self):
        return f'{self.number}'


class Region(models.Model):
    REGION_CHOICES = (
        ('chu', 'Чүй'),
        ('osh', 'Ош'),
        ('bat', 'Баткен'),
        ('jal', 'Жалал-Абад'),
        ('tal', 'Талас'),
        ('nar', 'Нарын'),
        ('kol', 'Ысык-Көл'),
        ('bis', 'г.Бишкек'),
        ('oshc', 'г.Ош'),
    )
    name = models.CharField(_('name'), max_length=9, choices=REGION_CHOICES, unique=True)
    address = models.CharField(_('address'), max_length=255)
    stat = models.CharField(_('stat'), max_length=255, null=True)

    class Meta:
        verbose_name = _('Region')
        verbose_name_plural = _('Regions')

    def __str__(self):
        return f'{dict(self.REGION_CHOICES)[self.name]}'


class District(models.Model):
    name = models.CharField(_('name'), max_length=55)
    region = models.ForeignKey(Region, models.CASCADE, verbose_name=_('region'))
    gov_admin = models.CharField(max_length=255, verbose_name='Мам админстрация башчы (ААТ)')
    stat_admin = models.CharField(max_length=255, verbose_name='Статистика башчы (ААТ)')
    counter = models.CharField(max_length=6, default='000001')
    center = models.CharField(_('center of district'), max_length=255, null=True, blank=True)
    agreement_ky = models.CharField(max_length=255, null=True, blank=True)
    agreement_ru = models.CharField(max_length=255, null=True, blank=True)
    stat_address = models.CharField(max_length=255, null=True, blank=True)
    did = models.CharField(max_length=2, null=True, blank=True)

    class Meta:
        verbose_name = _('District')
        verbose_name_plural = _('Districts')

    def __str__(self):
        return f'{self.name}'


def increment_territory_country():
    last_territory = Territory.objects.order_by('counter').last()
    if not last_territory:
        return '0001'
    return '{:04}'.format(int(last_territory.counter) + 1)


class Territory(models.Model):
    name = models.CharField(_('name'), max_length=90)
    code = models.CharField(_('code'), max_length=14, unique=True)
    district = models.ForeignKey(District, models.CASCADE)
    counter = models.CharField(max_length=4, default=increment_territory_country,
                               editable=False, unique=True)

    class Meta:
        verbose_name = _('Territory')
        verbose_name_plural = _('Territories')
        ordering = ['code']

    def __str__(self):
        return f'{self.name}'


class Employee(models.Model):
    GENDER_CHOICES = (
        ('2', _('male')),
        ('1', _('female')),
    )
    ROLE_CHOICES = (
        ('cor', _('Coordinator')),
        ('enum', _('Enumerator')),
        ('enum1', _('Enumerator1')),
        ('ins', _('Instructor')),
    )
    EDUCATION_CHOICES = (
        ('1', _('bachelor')),
        ('2', _('specialist')),
        ('3', _('master')),
        ('4', _('incomplete higher education')),
        ('5', _('specialized secondary education')),
        ('6', _('initial vocational training')),
        ('7', _('general secondary education')),
        ('8', _('lower secondary education'))
    )
    WORKDAY_CHOICES = (
        ('full', _('full time work')),
        ('half', _('half time work'))
    )

    number = models.CharField(_('number'), max_length=255, validators=[phone], unique=True,
                              error_messages={'unique': "Мундай номер бар."})
    last_name = models.CharField(_('last name'), max_length=45)
    first_name = models.CharField(_('first name'), max_length=45)
    patronymic = models.CharField(_('patronymic'), max_length=45, null=True, blank=True)
    gender = models.CharField(_('gender'), max_length=1, choices=GENDER_CHOICES, default='2')
    birth_day = models.DateField(_('birth day'))
    serial = models.CharField(_('serial'), max_length=2, choices=(('ID', 'ID'), ('AN', 'AN'), ('AC', 'AC')),
                              default='ID')
    passport_num = models.CharField(_('number of passport'), max_length=7)
    address = models.CharField(_('address'), max_length=255)
    authority = models.CharField(_('authority'), max_length=10)
    PIN = models.CharField(_('PIN'), max_length=14, unique=True)
    photo = models.ImageField(_('photo'), upload_to='users/img')
    education = models.CharField(_('education'), max_length=1, choices=EDUCATION_CHOICES, default=1)
    role = models.CharField(_('role'), max_length=50, choices=ROLE_CHOICES, default='cor')
    department = models.PositiveSmallIntegerField(_('census department'), default=1)
    sector = models.PositiveSmallIntegerField(_('coordinator sector'), default=1)
    plot = models.PositiveSmallIntegerField(_('enumerator plot'), default=1)
    district = models.ForeignKey(District, models.SET_NULL, verbose_name=_('district'), null=True, blank=True)
    territory = models.ForeignKey(Territory, models.SET_NULL, verbose_name=_('territory'), null=True, blank=True)
    workday = models.CharField(_('workday'), max_length=4, choices=WORKDAY_CHOICES, default='full')
    agreement = models.CharField(_('agreement'), max_length=6)
    date_joined = models.DateTimeField(_('date joined'), auto_now_add=True)
    is_badge_printed = models.BooleanField(_('is badge printed?'), default=False)
    is_badge_returned = models.BooleanField(_('is badge returned?'), default=False)
    dismissed = models.BooleanField(_('Dismissed?'), default=False)

    class Meta:
        verbose_name = _('Employee')
        verbose_name_plural = _('Employees')
        unique_together = (('district', 'agreement'), ('serial', 'passport_num'))
        ordering = ['-id']

    def get_absolute_url(self):
        return reverse('users:detail', args=[self.id])

    @property
    def get_role(self):
        return dict(Employee.ROLE_CHOICES).get(self.role)

    def __str__(self):
        return f'{self.first_name}'


@receiver(post_save, sender=Employee)
def set_agreement_number(sender, instance, created=False, **kwargs):
    if created:
        instance.agreement = "{:02}{:04}".format(int(instance.district.did), int(instance.district.counter))
        instance.district.counter = "{:06}".format(int(instance.district.counter) + 1)
        instance.district.save()
        instance.save()


class SingletonModel(models.Model):
    class Meta:
        abstract = True

    def delete(self, *args, **kwargs):
        pass

    def set_cache(self):
        cache.set(self.__class__.__name__, self)

    def save(self, *args, **kwargs):
        self.pk = 1
        super().save(*args, **kwargs)

    @classmethod
    def load(cls):
        obj, created = cls.objects.get_or_create(pk=1)
        return obj


class SiteSettings(SingletonModel):
    ROLE_CHOICES = (
        ('enum', _('Enumerator')),
        ('enum1', _('Enumerator1')),
        ('ins', _('Instructor')),
        ('cor', _('Coordinator')),

    )
    role = models.CharField(max_length=50, choices=ROLE_CHOICES, null=True)

    class Meta:
        verbose_name = 'Настройки сайта'
        verbose_name_plural = 'Настройки сайта'

    def __str__(self):
        return "Настройки сайта"


class RoleInfo(models.Model):
    ROLE_CHOICES = (
        ('enum', _('Enumerator')),
        ('enum1', _('Enumerator1')),
        ('ins', _('Instructor')),
        ('cor', _('Coordinator')),

    )
    site_settings = models.ForeignKey(SiteSettings, on_delete=models.CASCADE)
    role = models.CharField(max_length=50, choices=ROLE_CHOICES, null=True)
    salary = models.PositiveIntegerField(null=True)
    workday_start_date = models.DateField(null=True)
    workday_end_date = models.DateField(null=True)
    days_off = models.CharField(max_length=255, null=True, blank=True)
    agreement_day = models.DateField(null=True, blank=True)

users/forms.py
from django import forms
from django.forms import TextInput, PasswordInput
from django.utils.translation import ugettext_lazy as _
from users.models import phone, Employee, District, Territory, SiteSettings


class TelInput(TextInput):
    input_type = 'tel'


class HiddenSelectInput(forms.Select):
    input_type = 'hidden'


class UserLoginForm(forms.Form):
    number = forms.CharField(
        validators=[phone],
        widget=TelInput(attrs={'placeholder': '550XXXXXX',
                               'pattern': '^\d{9}$'}),
        label=_('number'))

    password = forms.CharField(
        widget=PasswordInput(),
        label=_('password'))

    next = forms.CharField(
        widget=TextInput(attrs={'hidden': True}),
        required=False)

    class Meta:
        fields = ['number', 'password', 'next']


class EmployeeCreateForm(forms.ModelForm):
    class Meta:
        model = Employee
        exclude = ['qrcode', 'agreement', 'login', 'password', 'is_badge_printed', 'is_badge_returned', 'photo',
                   'dismissed']
        widgets = {
            'number': TelInput(attrs={'class': 'form-control masked', 'placeholder': '555 500 000',
                                      'pattern': '\d{9}'}),
            'last_name': TextInput(attrs={'class': 'form-control'}),
            'first_name': TextInput(attrs={'class': 'form-control'}),
            'patronymic': TextInput(attrs={'class': 'form-control'}),
            'gender': forms.Select(attrs={'class': 'form-control'}),
            'birth_day': forms.DateInput(
                attrs={'class': 'date form-control', 'placeholder': 'Мисалы: 31.12.2004'},
                format='%d.%m.%Y'),
            'serial': forms.Select(attrs={'style': 'text-transform: uppercase;', 'class': 'form-control'}),
            'passport_num': TelInput(attrs={'class': 'form-control'}),
            'address': TextInput(attrs={'class': 'form-control'}),
            'authority': TextInput(attrs={'style': 'text-transform: uppercase;', 'class': 'form-control'}),
            'PIN': TelInput(attrs={'class': 'form-control'}),
            'education': forms.Select(attrs={'class': 'form-control'}),
            'role': forms.Select(attrs={'class': 'form-control'}),
            'department': TextInput(attrs={'class': 'form-control'}),
            'sector': TextInput(attrs={'class': 'form-control'}),
            'plot': TextInput(attrs={'class': 'form-control'}),
            'territory': forms.Select(attrs={'class': 'form-control'}),
            'workday': forms.Select(attrs={'class': 'form-control'}),
            'district': forms.HiddenInput(
                attrs={'class': 'text-dark font-weight-bold form-control'}),
        }

    def __init__(self, user, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['district'].queryset = District.objects.filter(user=user)
        self.fields['district'].initial = District.objects.first()
        self.fields['district'].empty_label = None
        self.fields['territory'].queryset = Territory.objects.filter(district=user.district)


class EmployeeUpdateForm(forms.ModelForm):
    class Meta:
        model = Employee
        exclude = ['qrcode', 'agreement', 'login', 'password', 'district', 'photo']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        initial = kwargs.get('initial')

        territory = initial.get('territory')

        self.fields['territory'].queryset = territory


class PhotoUpdateForm(forms.ModelForm):
    x1 = forms.CharField(widget=forms.HiddenInput(), required=False)
    y1 = forms.CharField(widget=forms.HiddenInput(), required=False)
    x2 = forms.CharField(widget=forms.HiddenInput(), required=False)
    y2 = forms.CharField(widget=forms.HiddenInput(), required=False)

    class Meta:
        model = Employee
        fields = ['photo']

templates/users/employee_confirm_delete.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% load widget_tweaks %}
{% load user_agents %}

{% block content %}
    <section>
        <div class="container">
            <form method="post">
                {% csrf_token %}
                <p>{% trans 'Are you sure you want to delete?' %}</p>
                <input type="submit" class="btn btn-danger" value="{% trans 'Delete' %}">
                <a href="{{ request.META.HTTP_REFERER|escape }}" class="btn btn-primary"> Айнуу </a>
            </form>
        </div>
    </section>
{% endblock %}

templates/users/photo_update.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% load widget_tweaks %}
{% load replace_asterisk %}
{% load users_extras %}

{% block head %}
    <style>
        .image-container {
            width: 500px;
            height: 500px;
        }

        img {
            width: 100%;
            height: 100%;
            object-fit: contain;
        }
    </style>
{% endblock %}

{% block content %}
    <div class="d-flex">
        <div class="image-container mx-auto">
            <img src="{% static 'img/nophoto.png' %}" alt="" id="image">
        </div>
    </div>
    <div class="d-flex">
        <form class="mx-auto" method="post" action="{% url 'users:update_photo' object.pk %}"
              enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">{% trans 'Save' %}</button>
            <a href="{{ request.META.HTTP_REFERER|escape }}" class="btn btn-secondary"> Артка </a>
        </form>
    </div>

{% endblock %}

{% block js %}
    <script>
        $(document).ready(function () {
            $("input[id='id_photo']").change(function () {
                let image = document.getElementById('image');
                let files = $(this)[0].files;
                let file = files[0];
                $('#image').attr('src', window.URL.createObjectURL(file));
                let cropper = new Cropper(image, {
                    aspectRatio: 3 / 4,
                    movable: false,
                    zoomable: false,
                    rotatable: true,
                    crop: function (e) {
                        $('#id_x1').val(Math.round(e.detail.x));
                        $('#id_y1').val(Math.round(e.detail.y));
                        $('#id_x2').val((Math.round(e.detail.x) + Math.round(e.detail.width)));
                        $('#id_y2').val((Math.round(e.detail.y) + Math.round(e.detail.height)));
                    }
                });
                cropper.crop();
            });
        });
    </script>
{% endblock %}

templates/users/update.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% load widget_tweaks %}
{% load replace_asterisk %}
{% load users_extras %}
{% load user_agents %}

{% block head %}
    <link rel="stylesheet" href="{% static 'fonts/Arial/stylesheet.css' %}">
{% endblock head %}

{% block title %}
    {% trans 'Home' %}
{% endblock %}
{% block content %}
    <div class="symbols no-print">
        <button value="Ө" onclick="insertSymbol(this)" class="symbol">Ө</button>
        <button value="Ү" onclick="insertSymbol(this)" class="symbol">Ү</button>
        <button value="Ң" onclick="insertSymbol(this)" class="symbol">Ң</button>
        <button value="ө" onclick="insertSymbol(this)" class="symbol">ө</button>
        <button value="ү" onclick="insertSymbol(this)" class="symbol">ү</button>
        <button value="ң" onclick="insertSymbol(this)" class="symbol">ң</button>
    </div>
    <section class="no-print mt-5">
        <div class="container">
            <div class="detail__header">
                <h1 class="detail-header__certificate">{% trans 'Certificate' %} &#8470;{{ object.agreement }}</h1>
                <h1 class="detail-header__role">{{ object.get_role }}</h1>
            </div>
            <div class="detail__items d-flex mt-5">
                <div class="image__item mx-auto">
                    {% if object.photo %}
                        <img src="{{ object.photo.url }}" alt="" class="image" style="object-fit: cover">
                    {% else %}
                        <img src="{% static 'img/nophoto.png' %}" alt="" class="image" style="object-fit: cover">
                    {% endif %}
                    {% if perms.users.change_employee %}
                        <a href="{% url 'users:update_photo' pk=object.pk %}"
                           style="display: block; text-align: center;">{% trans 'change image' %}</a>
                    {% endif %}
                </div>
            </div>
        </div>

        {% if request.user.is_authenticated %}
            <div class="container mt-5 no-print">
                <form action="{% url 'users:update' object.id %}" method="post" enctype="multipart/form-data"
                      id="update-form" data-ajax="false">
                    {% csrf_token %}
                    <fieldset>
                        {% for field in form.visible_fields %}
                            <div class="form-group row">
                                <label for="id_{{ field.name|lower }}"
                                       class="col-sm-3 col-form-label">{{ field.label }}</label>
                                <div class="col-sm-9">
                                    {% if field.name == 'photo' or field.name == 'is_badge_printed' or field.name == 'is_badge_returned' or field.name == 'dismissed' %}
                                        {% render_field field %}
                                    {% elif field.name == 'number' %}
                                        {% render_field field class="form-control masked" %}
                                    {% else %}
                                        {% render_field field class="form-control" %}
                                    {% endif %}
                                </div>
                            </div>
                        {% endfor %}
                    </fieldset>
                </form>
            </div>
            <div class="buttons-group mt-5 no-print">
                {% if perms.users.delete_employee %}
                    <a href="{% url 'users:delete' pk=object.pk %}" class="nav-item delete-btn">{% trans 'Delete' %}</a>
                {% endif %}
                {% if perms.users.change_employee %}
                    <button class="nav-item" onclick="update()">{% trans 'Update' %}</button>
                {% endif %}
                {% if request|is_pc and perms.users.can_print_badge %}
                    <button class="nav-item" onclick="printWindow()" id="badge_print">
                        <span class="fa fa-print" aria-hidden="true"></span>
                        {% trans 'Print' %}
                    </button>
                {% endif %}
            </div>
        {% endif %}
    </section>

    <section class="section__print">
        <div class="badge__main d-flex">
            <div class="badge__content mx-auto">
                <div class="badge-content__top">
                    <div class="employee__info">
                        <div class="employee-info__fio">
                            <p class="certificate">{% trans 'Certificate' %} &#8470;{{ object.agreement }}</p>
                            <p class="role">{{ object.get_role }}</p>
                            <p>{{ object.last_name|upper }}</p>
                            <p>{{ object.first_name|upper }}</p>
                            {% if object.patronymic %}
                                <p>{{ object.patronymic|upper }}</p>
                            {% endif %}
                        </div>
                        <div class="employee-info__image">
                            {% if object.photo %}
                                <img class="user-image" src="{{ object.photo.url }}" alt="">
                            {% else %}
                                <img class="user-image" src="{% static 'img/nophoto.png' %}" alt="">
                            {% endif %}
                        </div>
                    </div>
                </div>
                <div class="badge-content__bottom">
                    <div class="qr-code__container d-flex">
                        <img class="qr-code my-auto mx-auto" src="{{ object.qrcode.url }}" alt="">
                    </div>

                    <div class="admin-info__container">
                        <p>{% get_initials object.district.gov_admin %}</p>
                        <p class="badge-help">Райондук (шаардык) мамадминистрация башчысы-аким (мэр), колу</p>
                        <p>{% get_initials object.district.stat_admin %}</p>
                        <p class="badge-help">{% if object.district.id ==  44 or object.district.id == 26 %}
                            Облустук {% else %}Райондук{% endif %}(шаардык) мамстатистика жетекчиси, колу</p>
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock %}
{% block js %}
    <script src="{% static 'js/masking-input.js' %}" data-autoinit="true"></script>
    <script>
        $(document).ready(function () {
            $('.masked').mask('000000000', {'translation': {9: {pattern: '9'}, 6: {pattern: '6'}}});
            $('.date').mask('00.00.0000');
            $('#id_territory').val({{ object.territory.id }});

            if (window.localStorage) {
                if (!localStorage.getItem('firstLoad')) {
                    localStorage['firstLoad'] = true;
                    window.location.reload();
                } else {
                    localStorage.removeItem('firstLoad');
                }
            }

            $('#badge_print').on('click', function () {
                console.log("{{ object.last_name }}");
            });

            let role = $('#id_role option:selected').val();

            if (role == 'cor') {
                $('#id_department').parents('.form-group').css({
                    "display": "flex"
                });
                $('#id_sector').parents('.form-group').css({
                    "display": "none"
                });
                $('#id_plot').parents('.form-group').css({
                    "display": "none"
                });
            } else if (role == 'ins') {
                $('#id_department').parents('.form-group').css({
                    "display": "flex"
                });
                $('#id_sector').parents('.form-group').css({
                    "display": "flex"
                });
                $('#id_plot').parents('.form-group').css({
                    "display": "none"
                });
            } else if (role == 'enum') {
                $('#id_department').parents('.form-group').css({
                    "display": "flex"
                });
                $('#id_sector').parents('.form-group').css({
                    "display": "flex"
                });
                $('#id_plot').parents('.form-group').css({
                    "display": "flex"
                });
            }

            $('#id_role').change(function () {
                let role = $("#id_role option:selected").val();
                if (role == 'cor') {
                    $('#id_department').parents('.form-group').css({
                        "display": "flex"
                    });
                    $('#id_sector').parents('.form-group').css({
                        "display": "none"
                    });
                    $('#id_plot').parents('.form-group').css({
                        "display": "none"
                    });
                } else if (role == 'ins') {
                    $('#id_department').parents('.form-group').css({
                        "display": "flex"
                    });
                    $('#id_sector').parents('.form-group').css({
                        "display": "flex"
                    });
                    $('#id_plot').parents('.form-group').css({
                        "display": "none"
                    });
                } else if (role == 'enum') {
                    $('#id_department').parents('.form-group').css({
                        "display": "flex"
                    });
                    $('#id_sector').parents('.form-group').css({
                        "display": "flex"
                    });
                    $('#id_plot').parents('.form-group').css({
                        "display": "flex"
                    });
                }
            });
        });

        function update() {
            document.getElementById('update-form').submit();
        }
    </script>
{% endblock js %}